modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/Picono435/RandomTP/issues" #optional
license="GNU GENERAL PUBLIC LICENSE v3"
[[mods]] #mandatory
modId="randomtp" #mandatory
version="MC1.16.1-4.1.1" #mandatory
displayName="Random Teleport Mod" #mandatory
displayURL="https://www.piconodev.tk/" #optional
logoFile="logo.jpeg" #optional
credits="Thanks to everyone that helped me and PiconoDev growing." #optional
authors="Picono435" #optional
description='''
A mod that teleports you to a random location without colliding with lava, water or the world border.
'''